image: frekele/gradle

example-tests:
    tags:
        - java
    only:
        - master
    script:
        - gradle test -i
    artifacts:
        when: always
        name: reports
        paths:
            - reports/

# after_script:
#     - ls -R -a
