image: frekele/gradle

tests:
    tags:
        - java
    only:
        - master
    script:
        - gradle test

    artifacts:
        when: always
        name: reports
        paths:
            - reports/

cache:
    paths:
        - build
        - .gradle/caches

after_script:
    - ls -R -a
