tests: # the name of the build to run
    environment: # the environment to categorize the results
        name: student
    tags: # for selecting a compatibile runner
        - java
    only: # limit the branch to test
        - master
    script:
        # - echo Hello, world!
        - mvn test
