# image: maven

image: frekele/gradle

tests:
    tags:
        - java
    only:
        - master
    script:
        # - mvn test
        - gradle test

    artifacts:
        when: always
        name: reports
        paths:
            - reports/
