image: openjdk:8

provided-tests:
    environment:
        name: student
    tags:
        - java
    only:
        - master
    script:
        - echo Hello, world!
        # - gradle test
