image: openjdk:8

before_script:
    - apt-get install gradle

provided-tests:
    environment:
        name: student
    tags:
        - java
    only:
        - master
    script:
        - echo Hello, world!
        - gradle test
