image: openjdk:8

services:
    - maven:latest

provided-tests:
    environment:
        name: student
    tags:
        - java
    only:
        - master
    script:
        - echo Hello, world!
        - mvn test
