tests:
    tags:
        - java
    only:
        - master
    script:
        - mvn test
        - ls .
    # artifacts:
    #     when: always
    #     name: reports
    #     paths:
    #         - reports/
