image: frekele/gradle
# need to customize this image

example-tests:
    tags:
        - java
    only:
        - master
    script:
        - gradle test
    artifacts:
        when: always
        name: reports
        paths:
            - reports/
